# Generated by Django 3.2.12 on 2023-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVStationMaster', '0004_alter_stationdetails_paymodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='Area',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='Paymodes',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='dayTime',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='loc1',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='loc2',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='loc3',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='loc4',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='loc5',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='loc6',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='state',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='vehicleTypes',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
