# Generated by Django 3.2.12 on 2023-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVStationMaster', '0009_rename_stationid_slotbooking_stationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='stationName',
            field=models.CharField(default='_', max_length=255),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='stationRemark',
            field=models.TextField(default='_'),
        ),
    ]
