# Generated by Django 3.2.12 on 2023-11-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVStationMaster', '0002_auto_20231120_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='Area',
            field=models.CharField(max_length=255),
        ),
    ]
