# Generated by Django 3.2.12 on 2023-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVStationMaster', '0003_alter_stationdetails_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='Paymodes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
