# Generated by Django 3.2.12 on 2023-11-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVStationMaster', '0006_auto_20231120_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationdetails',
            name='vehicleTypes',
        ),
    ]
