# Generated by Django 3.2.12 on 2023-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVStationMaster', '0007_remove_stationdetails_vehicletypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.IntegerField()),
                ('customerName', models.CharField(max_length=255)),
                ('vehicleRegistration', models.CharField(max_length=20)),
                ('chargerType', models.CharField(max_length=255)),
                ('arrivalTime', models.DateTimeField()),
                ('status', models.CharField(default='Request Pending', max_length=255)),
                ('userRemark', models.TextField(default='-')),
                ('stationRemark', models.TextField(default='-')),
                ('unit', models.IntegerField()),
                ('time', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
